MechanicalVentilatorMilano/gui

- gui/communication/threading_utils.py
- gui/data_handler.py
- gui/default_settings.yaml
- gui/mainwindow.py
- gui/mvm_gui.py
- gui/settings/settings.ui
- mock/mock.ino
This PR solves issues #3, #4, #5, #7 and #8.
- general: removed a bunch of trailing whitespaces (sorry, it's my editor) and fixed a typo in a function name (eps->esp);
- issue #3: I've added a `_running` data member in the `DataHandler` class and a `stop_io()` method that sets the _running to `False` and waits for the thread pool to stop running;
- issue #4: I've removed the topmost tab bar and put all the widget of the "Setup" tab directly into the 
window; better widget arrangement;
- issue #5: I've implemented the feature to provide random numbers between 10 and 40 directly in the mockup so that it serves also a generator of fake data and removed the fake data generation from the Python code;
- issue #7: a global ESP32Serial object is create in the main file and passed to all classes …
> Solve a bunch of issues (3-5,7,8)

- gui/toolsettings/toolsettings.ui
To solve issue 13:
- Disabled sliders
> Disabled sliders

- README.md
- gui/data_filler.py
- requirements.txt
> x axis from -100 window_width to 0, improved readme file

- gui/monitor/monitor.ui
- Just swapped max and min in sidebar monitors
> Fixed backwards max/min

- gui/default_settings.yaml
- gui/monitor/monitor.ui
- Changed monitor font to Noto Mono (fixed width font)
> Issue 29 - fixed font in sidebar monitors

- gui/communication/esp32serial.py
- mock/mock.ino
The proposed solution to issue #12 is the following:
- add a read timeout of (by default, is tunable) one second
- read as much data as possible from the input buffer in the constructor (so discard it)
> Solve issue #12

- gui/mainwindow.py
The toggle mechanism for buttons has been greatly simplified, decomposing the code into different methods. Bugs fixed: now the buttons work seamlessly:
1. when push a button to start a mode
2. both buttons are disabled
3. the pushed button turn into a stop button and become active again
> Toggle buttons simplified + bugs fixed

- gui/default_settings.yaml
- gui/mainwindow.ui
- gui/monitor/monitor.py
- gui/monitor/monitor.ui
- gui/toolsettings/toolsettings.py
- gui/toolsettings/toolsettings.ui
Added better contrast by going to dark theme. Also did some space management to make the text more readable.
> Solved Issue 45

- gui/mainwindow.py
- gui/mainwindow.ui
- gui/start_stop_worker.py
Streamlined the start_stop_worker and changed the behavior of start/stop auto/assist UI.
Fixed apparent bugs with sending STOP even if not confirmed.
> New startstop ui

- gui/data_filler.py
- gui/default_settings.yaml
> Fixes #43 and #44

- README.md
Update README to include fakeESP32 command-line option
> update README for simulated input option

- gui/menu/menu.py
- gui/monitor/monitor.py
- gui/toolbar/toolbar.py
- gui/toolsettings/toolsettings.py
> issue #83 remove spurious show() calls

- gui/communication/esp32serial.py
- gui/data_handler.py
- gui/messagebox.py
- gui/mvm_gui.py
- gui/start_stop_worker.py
New messagebox.MessageBox class used for errors during startup, and communication errors while running.
> Issue 34 - Message box tools, plus better reporting of errors are startup

- gui/communication/esp32serial.py
- gui/communication/fake_esp32serial.py
- gui/default_settings.yaml
- gui/mvm_gui.py
implement the watchdog polling for the ESP32
as a temporary (?) patch requested by Andrea A., at program start the wdenable parameter is set.
> Issue #101

- gui/data_filler.py
Just need to update monitors even if plots are frozen.
> Issue 110 - still send alarms while plots are frozen

- gui/communication/fake_esp32serial.py
- gui/mvm_gui.py
> Added 'disableSimAlarms' command line option to mvm_gui

- gui/data_handler.py
- gui/mainwindow.py
Still need to hook-up the alarm class once ready, and send data to the alarm class as well.
> DataHandler now uses QTimer and not QThread

- gui/communication/fake_esp32serial.py
- gui/communication/fakeesp32.ui
- gui/default_settings.yaml
updates following PR #144 
addresses issue #143
> Issue 143 bis

- gui/communication/fake_esp32serial.py
- gui/data_filler.py
- gui/default_settings.yaml
- Fixes #133 
- Ensure there are at least N (configurable via yaml) major labelled ticks in the Y axis. 
- Also sets the space on the left of the Y axis (where the Y axis label is) to a constant value across all three plots, so as to ensure the Y axis is aligned across plots.
> Ensures at least 3 ticks in Y axes and aligns Y axes across plots

- gui/communication/fake_esp32serial.py
- gui/data_filler.py
- gui/default_settings.yaml
- gui/frozenplots/frozenplots.py
- gui/mainwindow.py
- gui/mainwindow.ui
- gui/menu/menu.py
- gui/menu/menu.ui
- gui/settings/settings.py
- gui/settings/settings.ui
- gui/special/special.py
- gui/special/special.ui
- gui/start_stop_worker.py
- gui/toolbar/toolbar.py
- mock/mock.ino
this PR solves issues #152 and #153
> Issue 152 and 153

- gui/alarm_handler.py
- gui/default_settings.yaml
- gui/menu/menu.ui
- gui/settings/settings.ui
- gui/special/special.py
- gui/start_stop_worker.py
waiting for the new observable from the `get all` command to be delivered from the firmware group, here is a first PR addressing issue #157
> Issue 157-first

- gui/alarms/alarms.py
- gui/default_settings.yaml
- gui/monitor/monitor.py
- gui/settings/mvmtoggle.py
- gui/settings/settings.py
- gui/settings/settings.ui
- gui/special/special.py
- gui/special/special.ui
this PR solves issue #160 #161 and #162
> Issue 160 161 162

- gui/special/special.py
this *should* solve issue #155
> use two different timers for the two pause modes

- gui/start_stop_worker.py
Fixed #170 
- A confirmation of start mode now pops up when pressing Start
> Added confirm start in start stop worker

- gui/alarms/guialarms.py
> added self to update_thresholds. issue 182

- gui/mainwindow.py
- gui/messagebar/messagebar.py
- gui/messagebar/messagebar.ui
- gui/special/special.py
- gui/start_stop_worker.py
- Added new `MessageBar` class for confirmations in the `bottombar`
- Reorganized start_stop_handler 
- Connected start_stop_handler to messagebar instead of messagebox
- *** Still need to do this for lung recruitment ***
> Issue 185 javier

- gui/alarm_handler.py
- gui/communication/esp32alarm.py
- gui/maindisplay/maindisplay.ui
- gui/mainwindow.py
- gui/mainwindow.ui
- Introduces an alarmbar (a top bar which is **always** on the top part of the GUI)
- If there is an alarm or a warning, this will appear in the form of a button in this alarm bar.
- The button shows the alarm or warning code.
- If the user clicks on the button, a string with the alarm or warning message is shown on the alarm bar and a snooze button appears
- If the user clicks on the snooze button, the alarm or warning button is removed and the alarm is snoozed in the esp.
- The buttons don't take all the available height in the alarmbar, I am still working on it.
> Issue 185 marco

- doc/example_esp32serial.py
- gui/alarms/alarms.py
- gui/data_filler.py
- gui/messagebox.py
- gui/numpad/numpad.py
- gui/settings/mvmtoggle.py
- gui/start_stop_worker.py
- gui/toolbar/toolbar.py
Running pylint on:
- gui/start_stop_worker.py
- gui/data_filler.py
- gui/alarms/alarms.py
- gui/numpad/numpad.py
- gui/example_esp32serial.py
- gui/messagebox.py
- gui/toolbar/toolbar.py
- gui/settings/mvmtoggle.py
NOTE: `example_esp32serial.py` is actually in the `doc` directory. There are many pylint warnings here, but I think we don't care?
Here is the current pylint output:
```
mac-133404:gui mdeltutt$ pylint start_stop_worker.py 
************* Module start_stop_worker
start_stop_worker.py:116:2: W0511: TODO: Cannot have pop up window (fixme)
start_stop_worker.py:155:2: W0511: TODO: find a good exit point (fixme)
start_stop_worker.py:335:2: W0511: TODO: this should be an alarm (fixme)
start_stop_worker.py:99:15: W0703: Catching too general exception Exception (broad-except) …
```
> Issue 184 marco

- gui/data_handler.py
- gui/mainwindow.py
- gui/messagebar/messagebar.py
- gui/monitor/monitor.py
- gui/settings/settings.py
- gui/settings/settingsfile.py
Taking care of the following files:
- `gui/mainwindow.py`: 9.40
- `gui/monitor/monitor.py`: 10
- `gui/settings/settings.py`: 9.66
- `gui/data_handler.py`: 9.77
- `gui/messagebar/messagebar.py`: 10
- `gui/settings/settingsfile.py`: 10
```
$ pylint mainwindow.py 
************* Module mainwindow
mainwindow.py:191:2: W0511: TODO: connect to circuit test on ESP (fixme)
mainwindow.py:9:0: E0611: No name 'settings' in module 'settings' (no-name-in-module)
mainwindow.py:10:0: E0611: No name 'settingsfile' in module 'settings' (no-name-in-module)
mainwindow.py:373:15: W0212: Access to a protected member _state of a client class (protected-access)
mainwindow.py:374:16: W0212: Access to a protected member _state of a client class (protected-access)
mainwindow.py:378:16: W0212: Access to a protected …
```
> Issue 184 carmelo

- gui/alarm_handler.py
- gui/alarms/guialarms.py
- gui/communication/peep.py
- gui/presets/presets.py
- gui/toolsettings/toolsettings.py
Implementation of recommendation from pylint of:
53	gui/communication/peep.py
21	gui/toolsettings/toolsettings.py
19	gui/alarm_handler.py
16	gui/alarms/guialarms.py
9	gui/communication/esp32serial.py
8	gui/presets/presets.py
Remaining errors are below.
************* Module communication.peep
communication/peep.py:25:0: C0103: Class name "peep" doesn't conform to PascalCase naming style (invalid-name)
************* Module toolsettings
toolsettings/toolsettings.py:58:4: R0913: Too many arguments (8/5) (too-many-arguments)
toolsettings/toolsettings.py:58:70: W0613: Unused argument 'dec_precision' (unused-argument)
toolsettings/toolsettings.py:58:87: W0613: Unused argument 'current' (unused-argument)
************* Module alarm_handler
alarm_handler.py:118:4: R0913: Too many arguments (6/5) …
> Issue 184 ben

- gui/communication/esp32alarm.py
- gui/communication/fake_esp32serial.py
- gui/frozenplots/frozenplots.py
- gui/special/special.py
Fixed pylint errors on the following:
- 59	 gui/frozenplots/frozenplots.py (9.71)
- 26	 gui/communication/fake_esp32serial.py (10)
- 19	 gui/special/special.py (9.07)
- 17	 gui/communication/esp32alarm.py (9.76)
The following does not exist in the repo so was not fixed...
- 8	 gui/settings/test_settingsfile.py
> Issue 184 javier

- mock/mock.ino
Updated `get all` to return float and bool.
> "get all" returns float and bool

- gui/tests/test_peep.py
Fixes #211
- `t5` -> `phase_start["restart"]`
- `t0` -> `t_cycle_start`
> update variables used in the test

- gui/default_settings.yaml
> settings.txt path changed to /storage/pi

- gui/calibration/spirometer.py
- gui/calibration/spirometer.ui
- gui/communication/fake_esp32serial.py
- gui/mainwindow.py
Addressing issue #232
Implemented:
- `venturi_calibration` function in `FakeESP32`
- almost complete implementation of the `SpirometerCalibration` class
> Issue 232 carmelo

- gui/mainwindow.py
- gui/mainwindow.ui
- gui/selftest/selftest.py
- gui/selftest/selftest.ui
- gui/selftest/selftestbar.py
- gui/selftest/selftestbar.ui
SelfTest partial implementation
- stacked widget for guiding the user through the self test defined
- movements between self-test pages defined
- placeholder functions to perform self tests added
> Issue 232 marco

- gui/default_settings.yaml
> convert also the PEEP value returned by "get all"

- gui/default_settings.yaml
Fixed #259 
- temperature max set to 75 C and monitor turns red when above this value
> Added temperature alarm (75C) to yaml file
